### ISSUE TITLE
Facilitate creating documentation requests of this site - capture slack conversations

### ISSUE THREAD

**Issue by bess** [projecthydra/projecthydra.github.io#64]
And what's the slack integration for this?

**Comment by jenlindner** [comment]
Looking for a way to capture slack questions and link to our (upcoming) documentation issue request/template. So that, a question in slack can be tagged to bring up a link to create a documentation issue for it.

**Comment by mjgiarlo** [comment]
:+1: to a "How to Ask for Help" document! This will be super helpful. It could cut down on some of the routine questions about sharing code, digging up tracebacks, etc. and make support questions more readily actionable.

**Comment by jenlindner** [comment]
@mjgiarlo thanks! I want to implement a slackbot response in the hydra slack dev and doc channels, to show the link to the new doc issue template - https://www.bettercloud.com/monitor/the-academy/how-to-create-custom-slackbot-responses-in-slack/. To respond to a term like doc_issue, for example. Would that be okay?

**Comment by mjgiarlo** [comment]
@jenlindner Sure, let's try it. :)

**Comment by jenlindner** [comment]
@mjgiarlo thanks! cool :-)

**Comment by jenlindner** [comment]
Okay, we have a slackbot now in ProjectHydra slack that opens a new ProjectHydra.io Documentation issue any time someone types this "doc.new", and the issue is made from a template of helpful guidelines like 'Descriptive summary of request', 'Existing Documentation.' At the moment, a great deal of community discussion happens in Slack, but the issue template itself will be helpful to anyone wanting to request more or better documentation in this site.
